- name: nginx installation
  hosts: local
  connection: localS
  become: yes
  tasks:
    - name: installation of nginx
      ansible.builtin.package:
        name: nginx
        status: present
        use: dnf

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        status: started
        enabled: yes
