- name: playbook variables
  hosts: local
  connection: local
  tasks: 
    - name: variables
      ansible.builtin.debug:
        msg: "I'm learning {{Course}} with a duration of {{Duration}} trained by {{Trainer}}"
  
