- name: playbook variables
  hosts: local
  connection: local
  tasks: 
    - name: variables
      ansible.builtin.debug:
        msg: "I'm learning {{course}} with a duration of {{duration}} trained by {{trainer}}"
  
